name: Deploy to Kubernetes
on:
  workflow_call:
    inputs:
      manifests:
        type: string
        description: 'Arquivos de manifesto para deploy'
        required: true
      images:
        type: string
        description: 'Imagens Docker para atualizar no Kubernetes'
        required: true
jobs:
    deploy-k8s:
       runs-on: ubuntu-latest
       steps: 
          - name: Obtendo o código
            uses: actions/checkout@v4.1.5
          - name: Configuração de contexto do Kubernetes
            uses: azure/k8s-set-context@v4.0.0
            with:
              method: kubeconfig
              kubeconfig: ${{ secrets.K8S_CONFIG }}
          - name: Execução do Manifesto
            uses: Azure/k8s-deploy@v5
            with:
                manifests: |
                  ${{ inputs.manifests }}
                images: |
                  ${{ inputs.images }}
